Desktop/workspace/group_project/group_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from library import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='index'),
    path('library/', include('library.urls')),
    # The above maps any URLs starting with library/ to be handled by library.
    path('admin/', admin.site.urls),
    path('register/', include('library.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Desktop/workspace/group_project/library/urls.py
from django.urls import path
from library import views
from django.views.decorators.csrf import csrf_exempt

app_name = 'library'

urlpatterns = [
    path('', views.index, name='index'),
   
    path('about/', views.About, name='about'), 
    path('bookpage/', views.BookPage, name='bookpage'),
    path('bookp/<int:id>/', views.detail, name='detail'),
    path('bookpage/', views.BookPage, name='bookpage'),
    path('login/', views.LogIn, name='login'),
    path('register/', views.Register, name='register'),
    path('favouritesList/', views.Favourites_List, name ='Favourites_List'),
    path('<int:id>/favourites/', views.Favourites, name='favourites'),
    path('validate-username/', csrf_exempt(views.validateUserName), name="validate-username"),
    path('validate-email/', csrf_exempt(views.validateEmail), name ='validate_email'),
    path('<slug:genre_name_slug>/',views.show_genre, name='show_genre'),
    path('logout/', views.user_logout, name='logout'),
    path('addreview/<int:id>/', views.add_review, name = "add_review"),
   

]

Desktop/workspace/group_project/library/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User

class Genre(models.Model):
    name = models.CharField(max_length=128, unique=True)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(unique=True, null=True)
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Genre, self).save(*args, **kwargs)
        
    class Meta:
        verbose_name_plural = 'genres'
            
    def __str__(self):
        return self.name

    
class Book(models.Model):
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE)
    title = models.CharField(max_length=128)
    url = models.URLField()
    quantity = models.IntegerField(default=0)
    likes = models.IntegerField(default = 0)
    favourites = models.ManyToManyField(User, related_name='favorite', blank=True)

    def __str__(self):
        return self.title

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    def __str__(self):
        return self.user.username

class Bookpage(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE, blank=True, null=True)
    name = models.CharField(max_length=128)

    def __str__(self):
        return self.name

class Review(models.Model):
    book = models.ForeignKey(Book, on_delete= models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.TextField(max_length=500)
    rating = models.FloatField(default=0)

    def __str__(self):
        return self.user.username

Desktop/workspace/group_project/library/forms.py
from django.contrib.auth.models import User
from library.models import UserProfile
from django import forms
from library.models import Review


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta:
        model = User
        fields = ('username', 'email', 'password',)

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ('comment', 'rating',)

Desktop/workspace/group_project/library/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.http import JsonResponse
from library.models import Genre, Book, Bookpage
from django.contrib.auth.models import User
import json
from validate_email import validate_email
from library.forms import UserForm, ReviewForm
from django.contrib.auth import authenticate, login
from django.urls import reverse
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.views.generic import ListView, DetailView
from library.models import Book, Review
from django.http import HttpResponse
from django.http import HttpResponseRedirect

from django.db.models import Avg

def index(request):

    genre_list = Genre.objects.all()
    context_dict = {}
    context_dict['genres'] = genre_list
    return render(request, 'library/index.html', context=context_dict) 

def show_genre(request, genre_name_slug):

    context_dict = {}
    
    try:
        genre = Genre.objects.get(slug=genre_name_slug)
        books = Book.objects.filter(genre=genre)

        context_dict['books'] = books
        context_dict['genre'] = genre

    except Genre.DoesNotExist:
        context_dict['genre'] = None
        context_dict['books'] = None

    return render(request, 'library/genre.html', context=context_dict)



def About(request):

    return render(request, 'library/about.html')


def LogIn(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return redirect(reverse('library:index'))
            else:
                return HttpResponse("Your Waterstones account is not active.")
        else:
            print(f"Invalid login details: {username}, {password}")
            return HttpResponse("Invalid login details supplied.")
    else:
        return render(request, 'library/LogIn.html')



#username validation using json
def validateUserName(request):
    data=json.loads(request.body)
    username=data['username']
    
    # check that string contains alphaneumericals and numbers
    if not str(username).isalnum():
        return JsonResponse({'username_error': 'username should only contain alphaneumerical letters and numbers, no spaces allowed.'}, status=400)   
    return JsonResponse({'username_valid': True})
    # check of username already exists
    if User.objects.filter(username=username).exists():
        return JsonResponse({'username_error': 'username already exists. Please try another one.'}, status=409)   
    return JsonResponse({'username_valid': True})

#Email validation usin json and the validate-email library
def validateEmail(request):
    data=json.loads(request.body)
    email=data['email']
    
    # check that email is correct
    if not validate_email(email):
        return JsonResponse({'email_error': 'Email is invalid, please try again'}, status=400)   
    # check of email already exists
    if User.objects.filter(email=email).exists():
        return JsonResponse({'email_errir': 'email already exists. Please try another one.'}, status=409)   
    return JsonResponse({'email_valid': True})

    

def Register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(request.POST)
        if user_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            registered = True
        else:
            print(user_form.errors,)
    else:
        user_form = UserForm()
    return render(request,
    'library/Register.html',
    context = {'user_form': user_form,
    'registered': registered})

def BookPage(request):

    return render(request, 'library/bookpage.html')


@login_required
def user_logout(request):
    logout(request)
    return redirect(reverse('library:index'))

def detail(request, id):
    book = Book.objects.get(id = id)
    reviews = Review.objects.filter(book = id)
    is_favorite = False    
    if book.favourites.filter(id = request.user.id).exists():
        is_favorite= True

    context_dict = {
        "book": book,
        "reviews": reviews,
        "is_favorite": is_favorite
    }
    return render(request, 'library/BookPage.html', context=context_dict)


def Bookp(request, genre_name_slug):
    context_dict = {}
    
    try:
        genre = Genre.objects.get(slug=genre_name_slug)
        books = Book.objects.filter(genre=genre)
        bookpage = Bookpage.objects.all
        
        context_dict['books'] = books
        context_dict['genre'] = genre
        context_dict['bookpage'] = bookpage

    except Genre.DoesNotExist:
        context_dict['genre'] = None
        context_dict['books'] = None
        context_dict['bookpage'] = None

    return render(request, 'library/Bookp.html',context=context_dict)

def add_review(request, id):
    if request.user.is_authenticated:
        book = Book.objects.get(id=id)
        if request.method == "POST":
            form = ReviewForm(request.POST)
            if form.is_valid():
                reviewdata = form.save(commit=False)
                reviewdata.comment = request.POST["comment"]
                reviewdata.rating = request.POST["rating"]
                reviewdata.user = request.user
                reviewdata.book = book
                reviewdata.save()
                return redirect("library:detail", id)
        else:
            form = ReviewForm()
        return render(request, 'library/bookp.html', {"form": form})
    else:
        return redirect("library:login")

def Favourites_List(request):
    user = request.user
    favourite_book = user.favorite.all()
    context_dict = {
        'favourite_book': favourite_book,
    }
    return render(request, 'library/Favorites.html', context = context_dict)

@ login_required
def Favourites(request, id):
    book = Book.objects.get(id = id)
    if book.favourites.filter(id=request.user.id).exists():
        book.favourites.remove(request.user)
    else:
        book.favourites.add(request.user)
    return redirect("library:detail", id)

Desktop/workspace/group_project/templates/library/About.html
<!DOCTYPE html>
{% load staticfiles %}


    <html>
    
        <head>
    
            <!-- The link tag below adds bootstrap--> 
            <link rel="stylesheet" 
            href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" 
            integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" 
            crossorigin="anonymous">
    
            <!-- The link tag below links the html file to the CSS file-->
			<link rel="stylesheet" type="text/css" href="{% static 'CSS/About.css' %}" />

            
            <title>
                About
            </title>
    
        </head>
    
    
        <h1 id = "heading">
            Glasgow Library
        </h1>
		


    
        <div id = "logInBigDiv">
            <body>
                
    
                <div id = "logInBox">
                    <h4>
                        About Us
                    </h4>
    
                    <p>
                        Waterstones is Glasgow's first e-library that enables the 
                        students of Glasgow to read and educate themselves free of charge
                        This is an attempt to motivate students to constantly read without
                        worrying about a pric to pay. Without a physical store, students 
                        reserve a book that intrigues them and we will ship it to them within
                        1-2 business days. Students are able to reserve a book for 30 days,
                        and will be asked to return the book
                    </p>
    
                </div>
                
    
            </body>
        </div>
    
        <h5 id = "heading">
        	<a href="http://127.0.0.1:8000/">
            	<button id = "navLogInButton">Home</button>
        	</a>
        </h5>
		
		
    </html>

Desktop/workspace/group_project/templates/library/Bookp.html
{% extends 'library/BookPage.html' %}
{% load staticfiles %}

{% block title_block %} 
	{% if genre %}
		{{ genre.name }}
    {% else %}
        Unknown genre
    {% endif %}
{% endblock %}



{%block body_block%}

	{% if genre %}
		{% if books %}
			{% if bookpage %}
				{% for bp in bookpage %}
				
					{% if bp.name == "FING" %}
						
						
				         <div class = "row" id = "book">

				             <div class = "col-md-6 col-sm-6 col-xs-6">
				                 <img src = "{% static 'images/C6.jpg' %}" width = "300">
				             </div>

				             <div class = "col-md-6 col-sm-6 col-xs-6" id = "book2">
				                 <h1 class = "bookDesc">{{bp.name}}</h1>
				                 <h2 class = "bookDesc">Genre: {{genre.name}}</h2>
				                 <h2 class = "bookDesc">Copies Available: 5</h2>
				                 <a href="">
				                     <button id = "reserve">
				                         Reserve
				                     </button>
				                 </a>

				                 <a href="">
				                     <button id = "wish">
				                         Wishlist
				                     </button>
				                 </a>



				             </div>

				         </div>


				         <div class = "genreType">
				             <p class = "genreTypeTitle">
				                 Other Similar Books
				             </p>
				         </div>

				         <div class = "row" id = "genreOne">

    
				                 <img src = "{% static 'images/F2.jpg' %}"
				                 class = "col-md-3 col-sm-3 col-xs-3" id = "genrePic">
            
				                 <img src = "{% static 'images/F3.jpg' %}"
				                 class = "col-md-3 col-sm-3 col-xs-3" id = "genrePic">
       
				                 <img src = "{% static 'images/F4.jpg' %}"
				                 class = "col-md-3 col-sm-3 col-xs-3" id = "genrePic">
        
				                 <img src = "{% static 'images/F5.jpg' %}"
				                 class = "col-md-3 col-sm-3 col-xs-3" id = "genrePic">


				         </div>


				         <div class="card">
							<div class="card-body">
								<h3 class="text-center">Add Review</h3>
								<form action="{% url 'library:add_review' book.id %}" method="POST">
									{% csrf_token %}
									<label for="comment">Review</label>
									<textarea name="comment" id="comment" cols="30" rows="5" class="form-control"></textarea>
					
									<label for="rating">Rating</label>
									<input type="text" name="rating" class="form-control">

									<br>
									<input type="submit" class="btn btn-danger" value="Add Review">
								</form>
							</div>
						 </div>
						 <div class="card-body">
							<ul>
								{% for review in reviews %}
								<li> {{ review.comment }} <i> {{ review.user }}</i></li>
								{% endfor %}
							</ul> 
						 </div>
					{% endif %}	
					
										
				{% endfor %}
			{% endif %}
		{% endif %}
	{% endif %}	
{% endblock %}

Desktop/workspace/group_project/templates/library/LogIn.html
<!DOCTYPE html>
{% load staticfiles %}

<html>

    <head>

        <!-- The link tag below adds bootstrap-->
        <link rel="stylesheet"
        href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
        integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z"
        crossorigin="anonymous">

        <!-- The link tag below links the html file to the CSS file-->
        <link rel="stylesheet" type="text/css" href="{% static 'CSS/LogIn.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'CSS/Homepage.css' %}" />

        <title>
            Log In
        </title>

    </head>


    <h1 id = "heading">

        Glasgow Library
    </h1>


    <div class="row">
        <div class="col-md-5"></div>
        <div class="cold-md-4">
          <div class="card mt-5">
      
            <div class="card-body">
              <div class="card-title py-3">
                <h4>Login To Your Account! </h4>
              </div>
              <form id="login_form" action="{% url 'library:login' %}" method="POST">
                {% csrf_token %}
                <div class="form-group">
                Username: <input type="text" name="username" value="" size="50" />
                </div>
                <div class="form-group">
                Password: <input type="password" name="password" value="" size="50" />
                </div>
                <br />

                <input type="submit" value="Login" class="btn btn-block btn-primary submitButton" />
              </form>
            </div>
            <div>
              <ul>
                <div class="mt-4">
                  <div class="d-flex justify-content-center links ">
                    Don't have an account? <li><a href="{% url 'library:register' %}">Sign Up!</a></li>
                  </div>
                </div>
                </ul>
                
            </div>
          </div>
        </div>
    </div>

</html>

Desktop/workspace/group_project/templates/library/Register.html
<!DOCTYPE html>
{% load staticfiles %}

<html>

    <head>

        <!-- The link tag below adds bootstrap-->
        <link rel="stylesheet"
        href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
        integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z"
        crossorigin="anonymous">

        <!-- The link tag below links the html file to the CSS file-->
        <link rel = "stylesheet" type = "text/css" href ="{% static 'CSS/LogIn.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'CSS/Homepage.css' %}" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha512-SfTiTlX6kk+qitfevl/7LibUOeJWlt9rbyDn92a1DqWOw9vWG2MFoays0sgObmWazO5BQPiFucnnEAjpAB+/Sw==" crossorigin="anonymous" />
        
    </head>

    <div class = "col-md-10 col-sm-4 col-xs-4">
      <h4 id = "heading">
         Glasgow Library
      </h4>
  </div>
<div class="row">
  <div class="col-md-4"></div>
  <div class="cold-md-4">
    <div class="card mt-5">

      <div class="card-body">
        <div class="card-title py-3">
          <h4>Register For a Free Account! </h4>
        </div>
        <form id="user_form" action="{% url 'library:register' %}" method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="form-group">
            {{ user_form.username }}
          </div>
        <div class ="invalid-feedback false-feedback" style = "display:none">
          </div>
          <p class="text-sm text-success successfullUsername"></p>
          <div class="form-group">
            {{ user_form.email }}
          
          </div>
          <div class ="invalid-feedback invalidEmailType" style = "display:none">
          </div>
          <p class="text-sm text-success successfullEmail"></p>
          <div class="form-group">
            {{ user_form.password }}
            <span>
              <i class="fa fa-eye float-right py-2" aria-hidden="true" id="eye" onclick="toggle()"></i>
              </span>
          </div>
          <script>
            var state = false;
            function toggle(){
              if(state){
                document.getElementById("passwordField").setAttribute("type","password");
                document.getElementById("eye").style.color="#7a797e";
                state= false;
              }else{
                document.getElementById("passwordField").setAttribute("type","text");
                document.getElementById("eye").style.color="#5887ef";
                state= true;
              }
            }
          </script>
          <input type="submit" value="Register" class="btn btn-block btn-primary submitButton" />
        </form>
      </div>
      <div>
        <ul>
          <div class="mt-4">
            <div class="d-flex justify-content-center links ">
              Already have an account? <li><a href="{% url 'library:login' %}">Login</a></li>
            </div>
          </div>
          </ul>
          
      </div>
        <div class="col-md-4"></div>
        <script>
          var form_fields = document.getElementsByTagName('input')
          form_fields[1].placeholder = 'Email';
          form_fields[1].id = 'usernameField'
          form_fields[1].className = 'form-control form-control-sm'

          form_fields[2].placeholder = 'Email';
          form_fields[2].id = 'emailField'
          form_fields[2].className = 'form-control form-control-sm'

          form_fields[3].placeholder = 'Password';
          form_fields[3].id = 'passwordField'
          form_fields[3].className = 'form-control form-control-sm'

          
        </script>
        <script src= "{% static 'js/register.js' %}"> </script>

</html>

Desktop/workspace/group_project/templates/library/index.html
<!DOCTYPE html>
{% load static %}


<html>
<style>
    .hello_message{
        font-size: 18px;
        color: black;
        margin-right: 100px;
    }
</style>
    <head>

        <!-- The link tag below adds bootstrap--> 
        <link rel="stylesheet" 
        href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" 
        integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" 
        crossorigin="anonymous">

        <!-- The link tag below links the html file to the CSS file-->
		<link rel="stylesheet" type="text/css" href="{% static 'CSS/Homepage.css' %}" />
		<link rel="stylesheet" type="text/css" href="{% static 'CSS/BookPage.css' %}" />

        <title>
			{% block title_block %}
				Glasgow Library
			{% endblock %}

        </title>

    </head>


    <div id = "bigDiv">

        <header class = "row" id = "topHeader">

             <!-- This is the code for the first row of content. 
            The classes for the below three divs split the screen
            in to three equal pieces of four columns each using bootstrap-->
            <div class = "col-md-4 col-sm-4 col-xs-4">
            </div>

            <div class = "col-md-4 col-sm-4 col-xs-4">
                <h4 id = "heading">
                 	Glasgow Library
                </h4>
            </div>
            <!-- fix this u cunt -->
            {% if user.is_authenticated %}
            <span class="hello_message">
            Welcome, {{ user.username }}
             </span>
             <span class="hello_message">
            <div class = "col-md-5 col-sm-5 col-xs-5" id = "logInDiv"></div>
                <a href="http://127.0.0.1:8000/library/register/">
                    <button id = "navLogInButton">Signout</button>
                </a>
            </span>
            {% else %}
            
        		<div class = "col-md-4 col-sm-4 col-xs-4" id = "logInDiv">
                <a href="http://127.0.0.1:8000/library/register/">
                	<button id = "navLogInButton">Register</button>
                </a>
                <a href="http://127.0.0.1:8000/library/login/">
                    <button id = "navRegisterButton">Log In</button>
                </a>
                </div>
                {% endif %}
			

        </header>

        <hr id = "divider">
        <!-- The header for bestsellers and search etc -->
        <header class = "row" id = "bottomHeader">

            <div class = "col-md-2 col-sm-2 col-xs-2">
                <a href = "http://127.0.0.1:8000/">
                    <p class = "headerItems">
                        BESTSELLERS
                    </p>
                </a>
            </div>

            <div class = "col-md-2 col-sm-2 col-xs-2">
                <a href = "http://127.0.0.1:8000/library/fiction/">
                    <p class = "headerItems">
			 			{% for genre in genres|slice:"2:3" %} 
							<a href="/library/{{ genre.slug }}/">{{ genre.name }}</a> 
						{% endfor %} 
                    </p>
                </a>
            </div>

            <div class = "col-md-2 col-sm-2 col-xs-2">
                <a href = "http://127.0.0.1:8000/library/nonfiction/">
                    <p class = "headerItems">
			 			{% for genre in genres|slice:":1" %} 
							<a href="/library/{{ genre.slug }}/">{{ genre.name }}</a> 
						{% endfor %}
                    </p>
                </a>
            </div>

            <div class = "col-md-2 col-sm-2 col-xs-2">
                <a href = "http://127.0.0.1:8000/library/children/">
                    <p class = "headerItems">
			 			{% for genre in genres|slice:"1:2" %} 
							<a href="/library/{{ genre.slug }}/">{{ genre.name }}</a> 
						{% endfor %}
                    </p>
                </a>
            </div>



            <div class = "col-md-4 col-sm-4 col-xs-4">
                <a href="{% url 'library:Favourites_List' %}">
                    <button id = "reservations">
                        WishList
                    </button>
                </a>
            </div>


        </header>


		{% block body_block %} 
        <body>
			
				
			

            <div>
				<img src="{% static 'images/P1.jpg' %}"
                id = "homePic">
            </div>

            <div class = "genreType">
                <p class = "genreTypeTitle">
                    <!-- add link to each page -->
                    Fiction
                </p>
            </div>

            <div class = "row" id = "genreOne">

        
                    <img src = "{% static 'images/F2.jpg' %}"
                    class = "col-md-3 col-sm-3 col-xs-3" id = "genrePic">
                
                    <img src = "{% static 'images/F3.jpg' %}"
                    class = "col-md-3 col-sm-3 col-xs-3" id = "genrePic">
           
                    <img src = "{% static 'images/F4.jpg' %}"
                    class = "col-md-3 col-sm-3 col-xs-3" id = "genrePic">
            
                    <img src = "{% static 'images/F5.jpg' %}"
                    class = "col-md-3 col-sm-3 col-xs-3" id = "genrePic">
					


            </div>
            <div class="row" id="bookTitlediv">
                <a href="http://127.0.0.1:8000/library/bookp/1/" id="bookTitle">The Girl with the Louding Voice</a>
                <a href="http://127.0.0.1:8000/library/bookp/2/" id="bookTitle">Girl, Woman, Other</a>
                <a href="http://127.0.0.1:8000/library/bookp/3/" id="bookTitle">The Guest List</a>
                <a href="http://127.0.0.1:8000/library/bookp/4/" id="bookTitle">Briefly Gorgeous</a>
            </div>

            <div class = "genreType">
                <p class = "genreTypeTitle">
                    Non-Fiction
                </p>
            </div>

            <div class = "row" id = "genreOne">

        
                    <img src = "{% static 'images/N2.jpg' %}"
                    class = "col-md-3 col-sm-3 col-xs-3" id = "genrePic">
                
                    <img src = "{% static 'images/N3.jpg' %}"
                    class = "col-md-3 col-sm-3 col-xs-3" id = "genrePic">
           
                    <img src = "{% static 'images/N4.jpg' %}"
                    class = "col-md-3 col-sm-3 col-xs-3" id = "genrePic">
            
                    <img src = "{% static 'images/N5.jpg' %}"
                    class = "col-md-3 col-sm-3 col-xs-3" id = "genrePic">


            </div>
            <div class="row" id="bookTitlediv">
                <a href="http://127.0.0.1:8000/library/bookp/9/" id="bookTitle">Becoming</a>
                <a href="http://127.0.0.1:8000/library/bookp/10/" id="bookTitle">The Boy, the Mole, the Fox, the Horse</a>
                <a href="http://127.0.0.1:8000/library/bookp/11/" id="bookTitle">House of Glass</a>
                <a href="http://127.0.0.1:8000/library/bookp/12/" id="bookTitle">Consensual Hex</a>
                </div>


            <div class = "genreType">
                <p class = "genreTypeTitle">
                    Children's
                </p>
            </div>

            <div class = "row" id = "genreOne">

        
                    <img src = "{% static 'images/C2.jpg' %}"
                    class = "col-md-3 col-sm-3 col-xs-3" id = "genrePic">
                
                    <img src = "{% static 'images/C3.jpg' %}"
                    class = "col-md-3 col-sm-3 col-xs-3" id = "genrePic">
           
                    <img src = "{% static 'images/C4.jpg' %}"
                    class = "col-md-3 col-sm-3 col-xs-3" id = "genrePic">
            
                    <img src = "{% static 'images/C5.jpg' %}"
                    class = "col-md-3 col-sm-3 col-xs-3" id = "genrePic">


            </div>
    
            <div class="row" id="bookTitlediv">
            <a href="http://127.0.0.1:8000/library/bookp/17/" id="bookTitle">Chain of Iron</a>
            <a href="http://127.0.0.1:8000/library/bookp/18/" id="bookTitle">Kay's Anatomy</a>
            <a href="http://127.0.0.1:8000/library/bookp/19/" id="bookTitle">One Hundred Steps</a>
            <a href="http://127.0.0.1:8000/library/bookp/20/" id="bookTitle">They Both Die at the End</a>
            </div>



            <div class = "genreType">
                <p class = "genreTypeTitle">
                    Our Best Picks
                </p>
            </div>

            <div class = "row" id = "genreOne">

        
                    <img src = "{% static 'images/F5.jpg' %}"
                    class = "col-md-3 col-sm-3 col-xs-3" id = "genrePic">
                
                    <img src = "{% static 'images/N5.jpg' %}"
                    class = "col-md-3 col-sm-3 col-xs-3" id = "genrePic">
           
                    <img src = "{% static 'images/F6.jpg' %}"
                    class = "col-md-3 col-sm-3 col-xs-3" id = "genrePic">
            
                    <img src = "{% static 'images/N7.jpg' %}"
                    class = "col-md-3 col-sm-3 col-xs-3" id = "genrePic">


            </div>
            <div class="row" id="bookTitlediv">
            <a href="http://127.0.0.1:8000/library/bookp/4/" id="bookTitle">Briefly Gorgeous</a>
            <a href="http://127.0.0.1:8000/library/bookp/12/" id="bookTitle">Consensual Hex</a>
            <a href="http://127.0.0.1:8000/library/bookp/5/" id="bookTitle">The Alchemist</a>
            <a href="http://127.0.0.1:8000/library/bookp/14/" id="bookTitle">How to Avoid a Climate Disaster</a>
            </div>

       <hr id = "divider">
	   
	   <!--
	   <div>
		   {% if genres %}
		   <ul>
			   {% for genre in genres %} 
				   <a href="/library/{{ genre.slug }}/">{{ genre.name }}</a> 
			   {% endfor %} 
		   </ul> 
		   {% else %}
		   <strong>There are no genres present.</strong> {% endif %}
	   </div>
		   -->
		   
        </body>
		{% endblock %}

        <footer>

            <div class = "row" id = "footer">
                <p id = "footerTitle"
                class = "col-md-3 col-sm-3 col-xs-3">
                Glasgow Library
                </p>

                <p id = "footerItem"
                class = "col-md-2 col-sm-2 col-xs-2">
                <a href = "http://127.0.0.1:8000/library/about/">
                    About Us
                </a>
                </p>



                <p id = "footerTrademark"
                class = "col-md-3 col-sm-3 col-xs-3">
                Glasgow Library, Inc. 2021. We love our users!
                </p>

            </div>
			
            </footer>
			        
        </footer>

    </div>



</html>